baseURL = "http://entirelydifferentmatters.github.io/"
languageCode = "en-us"
theme = "cactus"
title = "Entirely Different Matters"
[[menu.main]]
name = "About"
url = "/about"
weight = 4
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
colortheme = "dark"
description = "Occasional rants and essays"
googleAnalyticsAsync = true
mainSection = "posts"
postsOnHomePage = 5
projectsUrl = "https://github.com/gohugoio"
rss = false
showAllPostsArchive = false
showAllPostsOnHomePage = false
showProjectsList = false
showReadTime = true
show_updated = true
tagsOverview = true
[[params.social]]
link = "https://github.com/Kaapeine"
name = "github"
[[params.social]]
link = "https://www.linkedin.com/shrivathsams"
name = "linkedin"
[[params.social]]
link = "msshrivathsa@gmail.com"
name = "email"
